export const SUBCELL_CLICK = "SUBCELL_CLICK";

export const GRID_CONFIG_UPDATE = "GRID_CONFIG_UPDATE";

export const PATTERN_ADD = "PATTERN_ADD";
export const PATTERN_DELETE = "PATTERN_DELETE";
export const PATTERN_CHANGE_COLOR = "PATTERN_CHANGE_COLOR";