export const SUBCELL_CLICK = "SUBCELL_CLICK";
export const SUBCELL_UPDATE = "SUBCELL_UPDATE";

export const GRID_CONFIG_UPDATE = "GRID_CONFIG_UPDATE";

export const PATTERN_ADD = "PATTERN_ADD";
export const PATTERN_DELETE = "PATTERN_DELETE";
export const PATTERN_CHANGE_COLOR = "PATTERN_CHANGE_COLOR";

export const COLOR_PICKER_SHOW = "COLOR_PICKER_SHOW";